name: DemoForPullRequest

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**.sql'
env:
  base_branch: develop
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: install SQLFluff
        run: 'pip install sqlfluff'
      - name: download
        uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          reporter: github-pr-review
          sqlfluff_command: "lint"
          paths: '${{ github.workspace }}/sqls'
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
