name: CI

on:
  workflow_dispatch:

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      - uses: 'actions/setup-python@v2' 
        with:
            python-version: '3.10'
      - name: install SQLFluff
        run: 'pip install sqlfluff==0.13.1'
      - name: setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: format
        run: |
          for file in '/sqls/*.sql' 
          do
            faketty sqlfluff fix $file --rules L001,L002,L003,L004,L005,L006,L010,L011,L012,L017,L018,L019,L022,L023 --dialect bigquery -f
          done
      # 変更内容をコミット
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: run sqlfluff
