name: ValidateToml

on:
  push:
    paths:
      # TOML ファイル (.toml) をプッシュするたびに実行
      - '**.toml'
jobs:
  validate-toml:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Validate TOML file
        run: |
          for file in '**.toml'
          do
            echo "- target_file: ${file}"
            # jq . $file
            python .github/validate_toml.py $file
          done
