name: DemoForPullRequest

on:
  pull_request:
    branches:
      - 'releases/**'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: install SQLFluff
        run: 'pip install sqlfluff'
      - name: format
        run: |
          for file in 'sqls/*.sql' 
          do
            sqlfluff fix $file --dialect snowflake -f
          done
