name DemoWorkflowLinter

on:
  # Allows you to run this workflow manually from the Actions tab
#  push:
#    branches:
#      - your-branch
  workflow_dispatch:
    inputs:
      chosen-hello-world:
        required: true
        type: choice
        options:
        - Hello
        - World

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint with Ruff
        run: |
          ruff --output-format=github .
        continue-on-error: true
