name: ValidateToml

on:
  push:
    paths:
      # TOML ファイル (.toml) をプッシュするたびに実行
      - '**.toml'
env:
  base_branch: develop
jobs:
  validate-toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
        name: checkout "${{ github.base_ref }}"
        with:
          fetch-depth: 1
          ref: ${{ github.base_ref }}
      - uses: actions/checkout@v4
        name: checkout "${{ github.head_ref }}"
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref}}
      - name: Validate TOML file
        run: |
          # Run actions using diff_files
          diff_files=$(git diff --name-only HEAD ${base_branch} -- "**.toml" \
            | tr "\n" " ")
          echo "# diff_files: ${diff_files}"

          # 差分でループ
          for file in ${diff_files[@]}; do
            echo ${file}
            python .github/validate_toml.py $file
          done 
