name: DemoForPullRequest

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**.sql'
env:
  base_branch: develop
jobs:
  init-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: install SQLFluff
        run: 'pip install sqlfluff'
      - name: Switch to pull request branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch base branch
        run: git fetch origin ${base_branch}:${base_branch}
      - name: Run actions using diff_files
        run: |
          diff_files=$(git diff --name-only HEAD ${base_branch} -- "sqls/**.sql" \
            | tr "\n" " ")
          echo "# diff_files: ${diff_files}"

          for file in ${diff_files}
          do
            sqlfluff fix $file --dialect snowflake
          done
