name: DemoAnnotations

on:
  workflow_dispatch:

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable problem matcher
        run: |
           echo "::add-matcher::.github/demo_matcher.json"
        continue-on-error: true
      - name: Demo for Matchers
        run: |
           echo 'main.py:2:3: E111 indentation is not a multiple of four'
           echo 'main.py:2:3: E111 indentation is not a multiple of four'
        continue-on-error: true
      - name: Disable problem matcher
        run: |
          echo "::remove-matcher owner=user::"
