name: Run SQL linter with sqlfmt

on:
  workflow_dispatch:

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: 'actions/setup-python@v2' 
        with:
            python-version: '3.10'
      - name: install sqlfmt
        run: "pip install 'shandy-sqlfmt[jinjafmt]'"
      - name: format
        run: |
          sqlfmt --diff sqls
