name: DemoWorkflowLinter

on:
  workflow_dispatch:

jobs:
  sample-job:
    runs-on: ubuntu-latest
    # !! Fixing for "job should have permissions"
    permissions: {}
    steps:
      # !! Fixing for "action ref should be full length SHA1"
      # v4.1.2
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      # v4.8.0
      - name: Set up Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint with Ruff
        run: |
          ruff --output-format=github .
        continue-on-error: true
