name: Sample

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      chosen-hello-world:
        required: true
        type: choice
        options:
        - Hello
        - World

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p path/to/artifact
      - run: echo "hello World" > path/to/artifact/hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: path/to/artifact/hello.txt
          if-no-files-found: warn
          retention-days: 1
          overwrite: true
  job2:
    runs-on: ubuntu-latest
    steps: 
      - run: mkdir -p path/out/artifact
      - uses: actions/download-artifact@v4
        with:
          name: hello-artifact
          path: path/out/artifact
      - run: cat path/out/artifact/hello.txt
