# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      chosen-hello-world:
        required: true
        type: choice
        options:
        - Hello
        - World

env:
  DEMO_S3_PATH: s3://your-s3-bucket/xxxx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: If main
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "MESSAGE=Hello" >> $GITHUB_ENV
          echo "BRANCH_NAME=main" >> $GITHUB_ENV
      - name: If other
        if: ${{ github.ref_name != 'main' }}
        run: |
          echo "MESSAGE=World" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{github.ref_name}}" >> $GITHUB_ENV
      - name: Result
        run: echo "MESSAGE=${{ env.MESSAGE }}, BRANCH_NAME=${{ env.BRANCH_NAME }}"
