name: StartA

on:
  push:

jobs:
  init:
    runs-on: "ubuntu-latest"
    steps:
      - name: set for dev
        if: github.ref_name == 'develop'
        run: |
          value='[ "ubuntu-24.04" ]'
          echo "GITHUB_RUNS_ON=${value}" >> $GITHUB_ENV
      - name: set for stage
        if: github.ref_name == 'stage'
        run: |
          value='[ "ubuntu-22.04" ]'
          echo "GITHUB_RUNS_ON=${value}" >> $GITHUB_ENV
      - name: set for prod
        if: github.ref_name == 'prod'
        run: |
          value='[ "ubuntu-latest" ]'
          echo "GITHUB_RUNS_ON=${value}" >> $GITHUB_ENV
      - name: set value
        id: set-value
        run: |
          echo "ref_name = ${{ github.ref_name }}"
          echo "GITHUB_RUNS_ON = ${{ env.GITHUB_RUNS_ON }}"
          echo "github_runs_on=${{ env.GITHUB_RUNS_ON }}" >> $GITHUB_OUTPUT
    outputs:
      github_runs_on: ${{ steps.set-value.outputs.github_runs_on }}
  call_demo_workflow:
    needs: init
    uses: ./.github/workflows/test_a.yml
    with:
      runs_on: ${{ needs.init.outputs.github_runs_on }}
