name: TestA

on:
  workflow_dispatch:
    inputs:
      runs_on:
        type: choice
        default: ''
        options:
        - ubuntu-24.04
        - ubuntu-20.04
  push:
    branches:
      - develop
jobs:
  sample:
    runs-on: >-
      ${{
        inputs.runs_on != ''
          && fromJSON('["inputs.runs_on"]')
          || (github.ref_name == 'develop' && fromJSON('["ubuntu-latest"]')
          || fromJSON('["ubuntu-24.04"]'))
      }}
    steps:
      - name: Demo sample
        run: echo "Hello, world!!"

    
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
