name: TestA

on:
  workflow_call:
    inputs:
      runs_on:
        description: runs on
        default: ubuntu-latest
        type: string

jobs:
  greeting:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - id: message
        run: |
          echo "Hello world!!"
    
