name: DemoWorkflow

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        default: dev
        options:
        - dev
        - stage
        - prod
jobs:
  demo_job:
    runs-on: >-
      ${{
        (github.ref_name == 'develpe' && inputs.env == 'dev')
          && fromJSON('[ "ubuntu-20.04" ]')
          || ((github.ref_name != 'develpe' && inputs.env == 'dev') && fromJSON('["ubuntu-24.04" ]')
          || fromJSON('["ubuntu-latest" ]'))
      }}
    steps:
      - uses: actions/checkout@v4
      - name: settings
        run: |
          echo "Hello, world"
