name: Starter workflow for reusable workflow

on:
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/workflow-b.yml
    with:
      friend_name: Mike

  show_outputs:
    needs:
      - call_reusable_workflow
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.call_reusable_workflow.outputs.greeting_message }}
