name: Sample workflow for workflow_call

on:
  workflow_call:
    inputs:
      input_name:
        description: Fill name
        required: true
        type: string
    outputs:
      result_message:
        description: Result output message
        value: ${{ jobs.greeting.outputs.output_result }}

jobs:
  greeting:
    runs-on: ubuntu-latest
    outputs:
      output_result: ${{ steps.message.outputs.result }}
    steps:
      - id: message
        run: |
          echo 'result=Hi, ${{ inputs.input_name }}!' >> $GITHUB_OUTPUT
    
