name: Demo Workflow-B

on:
  workflow_call:
    inputs:
      constant_value:
        description: 'Input - constant-value'
        required: false
        type: string
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.job-b.outputs.job_output1 }}

jobs:
  job-b:
    runs-on: ubuntu-latest
    env:
      CONSTANT: ${{ inputs.constant-value }}
    steps:
      - id: step1
        run: echo "constant=${{ env.CONSTANT }}" >> $GITHUB_OUTPUT
    outputs:
      job_output1: ${{ steps.step1.outputs.constant }}
  
