name: Start workflow

on:
  workflow_dispatch:

jobs:
  call_demo_workflow:
    uses: ./.github/workflows/workflow-b.yml
    with:
      friend_name: Mike

  show_outputs:
    needs:
      - call_demo_workflow
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.call_demo_workflow.outputs.result_message }}
