name: Reusable workflow sample

on:
  workflow_call:
    inputs:
      friend_name:
        description: Fill in the friend name you want to greet
        required: true
        type: string
    outputs:
      greeting_message:
        description: Greeting message
        value: ${{ jobs.greeting.outputs.message }}

jobs:
  greeting:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.message.outputs.message }}
    steps:
      - id: message
        run: |
          echo 'message=Hi, ${{ inputs.friend_name }}!' >> $GITHUB_OUTPUT
    
