name: Demo Workflow-A

on:
  workflow_dispatch:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: Calling
        uses: ./.github/workflows/workflow-b.yml
        with:
          constant_value: "Hello World!!"
