name: Start workflow

on:
  workflow_dispatch:

env:
  INPUT_NAME: Smith

jobs:
  init:
    outputs:
      input_value: ${{ steps.init_values.outputs.input_value }}
    runs-on: ubuntu-latest
    steps:
      - id: init_values
        run: |
          echo 'input_value=${{ env.INPUT_NAME }}!' >> $GITHUB_OUTPUT
  call_demo_workflow:
    needs:
      - init
    uses: ./.github/workflows/workflow-b.yml
    with:
      input_name: ${{ needs.init.outputs.input_value }}

  show_outputs:
    needs:
      - call_demo_workflow
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.call_demo_workflow.outputs.result_message }}
