name: DemoWorkflow

on:
  workflow_dispatch:
    inputs:
      runs_on:
        type: choice
        default: ubuntu-latest
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-20.04
jobs:
  demo_job:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v4
      - name: settings
        run: |
          echo "Hello, world"
