name: Demo Workflow-A

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Enviroment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - stage
        - prod
      demoInputValue:
        description: 'Sample input'
        required: true
        type: string

jobs:
  job-a:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ inputs.env }}
      DEMO_INPUT_VALUE: ${{ inputs.demoInputValue }}
    steps:
      - uses: .github/workflows/deploy_to_ecs.yml
        with:
          env-value: ${{ env.ENV }}
          input-value: ${{ env.DEMO_INPUT_VALUE }}
          constant-value: "Hello World!!"

      
      service-name: sample-test-service
